# fly.toml app configuration file generated for datingappdv on 2023-10-31T20:58:23+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "datingappdv"
primary_region = "ams"

[build]
  image = "dennisrvalk/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dodw2ytnm"
  CloudinarySettings__ApiKey="385796717528113"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
